name: Update "On Repeat" Playlist

on:
  schedule:
    # Run every day
    - cron: 29 17 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: pages
        persist-credentials: false
        fetch-depth: 0
    - name: Create index.html
      run: |
        python3 main.py
    - name: Commit files
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add index.html
        git commit -m "Update Playlist"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: pages
